name = "safe-synthetix-module"
version = "0.0.1"

[setting.safe_package]
defaultValue = "safe:1.3.0"

[setting.safe_package_preset]
defaultValue = "main"

[setting.election_module_package]
defaultValue = "synthetix-election-module:latest"

[setting.safe_salt]
defaultValue = "fun"

[import.pdao_safe]
source = "<%= settings.safe_package %>"
preset = "<%= settings.safe_package_preset %>"

[import.election_module]
source = "<%= settings.election_module_package %>"

[contract.SynthetixSafeModuleRegistration]
artifact = "SynthetixSafeModuleRegistration"

[contract.SynthetixSafeModule]
artifact = "SynthetixSafeModule"
args = [
    "<%= imports.election_module.contracts.CoreProxy.address %>",
    "<%= imports.pdao_safe.contracts.Safe.address %>"
]

depends = ["import.pdao_safe", "import.election_module"]

[provision.target_safe]
source = "<%= settings.safe_package %>"
targetPreset = "<%= settings.safe_package_preset %>-sc"

options.salt = "<%= formatBytes32String(settings.safe_salt) %>"
options.initTo = "<%= contracts.SynthetixSafeModuleRegistration.address %>"
# setup(address)
options.initData = "0x66d38203<%= defaultAbiCoder.encode(['address'], [contracts.SynthetixSafeModule.address]).slice(2) %>" 

depends = ["contract.SynthetixSafeModule", "contract.SynthetixSafeModuleRegistration"]
