name = "infinex-council-safes"
version = "0.0.1"

# a dummy safe with an inaccessible signer is required to ensure
[provision.dummySafe]
source = "safe:1.3.0"
options.salt = "29372933292361"
options.owners = "0x0000000000000000000000000000000000000010"

[provision.ccCouncilSafe]
source = "safe-synthetix-module:0.0.1"
options.salt = "infinexCcCouncil"
options.election_module_address = "0x314bcf8bDc2b8f08587099455C961b5CE77B1f1b"
options.council_safe_address = "<%= imports.dummySafe.contracts.Safe.address %>"

[provision.ecosystemCouncilSafe]
source = "safe-synthetix-module:0.0.1"
#options.salt = "infinexEcosystemCouncil"
options.election_module_address = "0xCCF664ed84DcDedcC4783707993C12b5019D6693"
options.council_safe_address = "<%= imports.ccCouncilSafe.imports.target_safe.contracts.Safe.address %>"

[provision.treasurySafe]
source = "safe-synthetix-module:0.0.1"
#options.salt = "infinexTreasuryCouncil"
options.election_module_address = "0x16630c59bE96EbE58CfB79FDae34a52E46898494"
options.council_safe_address = "<%= imports.ecosystemCouncilSafe.imports.target_safe.contracts.Safe.address %>"
options.initial_veto_signers = "1"

[provision.treasuryVetoSafe]
source = "safe-synthetix-module:0.0.1"
#options.salt = "infinexTreasuryVeto"
options.election_module_address = "0xd4eadf38a70000473E4729a92F891821f703379f"
options.council_safe_address = "<%= imports.dummySafe.contracts.Safe.address %>"
options.initial_veto_signers = "0"
